import { useEffect, useState } from "react"; import { useParams, useNavigate, Link } from "react-router-dom"; import { Eye, Save, Image as ImageIcon, AlertCircle, ChevronLeft } from "lucide-react"; import { Button } from "@/components/ui/Button"; import { Input } from "@/components/ui/Input"; import { Textarea } from "@/components/ui/Textarea"; import { Select } from "@/components/ui/Select"; import { Label } from "@/components/ui/Label"; import { MarkdownRenderer } from "@/components/MarkdownRenderer"; import { fetchAdminPost, createPost, updatePost, fetchCategories, fetchTags, fetchMedia } from "@/lib/api"; import { ADMIN_BASE_PATH } from "@/App"; import type { Post, Category, Tag, MediaItem } from "@/types";
export function AdminPostEditPage() {
  const { id } = useParams<{ id: string }>(); const nav = useNavigate(); const isNew = id === "new"; const postId = id && !isNew ? parseInt(id, 10) : undefined;
  const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [excerpt, setExcerpt] = useState(""); const [content, setContent] = useState(""); const [categoryId, setCategoryId] = useState<number | "">(""); const [status, setStatus] = useState<"draft" | "published">("draft"); const [coverImageId, setCoverImageId] = useState<number | null>(null); const [metaTitle, setMetaTitle] = useState(""); const [metaDescription, setMetaDescription] = useState(""); const [canonicalUrl, setCanonicalUrl] = useState(""); const [sources, setSources] = useState(""); const [videoUrl, setVideoUrl] = useState(""); const [videoPoster, setVideoPoster] = useState(""); const [telegramDiscussionUrl, setTelegramDiscussionUrl] = useState(""); const [featured, setFeatured] = useState(false); const [viewCount, setViewCount] = useState(0); const [likeCount, setLikeCount] = useState(0); const [selectedTagIds, setSelectedTagIds] = useState<number[]>([]);
  const [categories, setCategories] = useState<Category[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [media, setMedia] = useState<MediaItem[]>([]); const [mediaOpen, setMediaOpen] = useState(false); const [preview, setPreview] = useState(false); const [loading, setLoading] = useState(!isNew); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetchCategories(), fetchTags(), fetchMedia()]).then(([c, t, m]) => { setCategories(c.data); setTags(t.data); setMedia(m.data); }); }, []);
  useEffect(() => { if (isNew || !postId) return; fetchAdminPost(postId).then(r => { const p = r.data; setTitle(p.title); setSlug(p.slug); setExcerpt(p.excerpt); setContent(p.content); setCategoryId(p.categoryId); setStatus(p.status); setCoverImageId(p.coverImageId); setMetaTitle(p.metaTitle || ""); setMetaDescription(p.metaDescription || ""); setCanonicalUrl(p.canonicalUrl || ""); setSources(p.sources || ""); setVideoUrl(p.videoUrl || ""); setVideoPoster(p.videoPoster || ""); setTelegramDiscussionUrl(p.telegramDiscussionUrl || ""); setFeatured(p.featured || false); setViewCount(p.viewCount || 0); setLikeCount(p.likeCount || 0); setSelectedTagIds((p.tags || []).map(t => t.id)); }).catch(err => setError(err.message)).finally(() => setLoading(false)); }, [postId, isNew]);
  const save = async (publishStatus?: "draft" | "published") => { setError(null); setSaving(true); const body: Partial<Post> & { categoryId: number; status: "draft" | "published"; tagIds: number[] } = { title, slug: slug || undefined, excerpt, content, categoryId: Number(categoryId), status: publishStatus || status, coverImageId, metaTitle: metaTitle || null, metaDescription: metaDescription || null, canonicalUrl: canonicalUrl || null, sources: sources || null, videoUrl: videoUrl || null, videoPoster: videoPoster || null, telegramDiscussionUrl: telegramDiscussionUrl || null, featured, tagIds: selectedTagIds }; try { if (isNew) await createPost(body); else if (postId) await updatePost(postId, body); nav(`${ADMIN_BASE_PATH}/posts`); } catch (err: any) { setError(err.message || "خطا در ذخیره‌سازی"); } finally { setSaving(false); } };
  const toggleTag = (tid: number) => setSelectedTagIds(prev => prev.includes(tid) ? prev.filter(x => x !== tid) : [...prev, tid]);
  if (loading) return <div className="flex min-h-[200px] items-center justify-center"><div className="h-8 w-8 animate-spin rounded-full border-2 border-ios-blue border-t-transparent" /></div>;
  return (
    <div>
      <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3"><Link to={`${ADMIN_BASE_PATH}/posts`}><Button variant="ghost" size="icon" className="rounded-full"><ChevronLeft className="h-5 w-5" /></Button></Link><h1 className="text-2xl font-bold text-label-primary">{isNew ? "مقاله جدید" : "ویرایش مقاله"}</h1></div>
        <div className="flex items-center gap-2"><Button variant="outline" onClick={() => setPreview(p => !p)} className="gap-2"><Eye className="h-4 w-4" />{preview ? "ویرایش" : "پیش‌نمایش"}</Button><Button variant="secondary" onClick={() => save("draft")} disabled={saving}>ذخیره پیش‌نویس</Button><Button onClick={() => save("published")} disabled={saving} className="gap-2"><Save className="h-4 w-4" />{saving ? "در حال ذخیره..." : "انتشار"}</Button></div>
      </div>
      {error && <div className="mb-4 flex items-center gap-2 rounded-ios bg-red-50 p-3 text-sm text-red-700 dark:bg-red-900/20 dark:text-red-300"><AlertCircle className="h-4 w-4" />{error}</div>}
      {preview ? <div className="rounded-ios border border-separator/30 bg-bg-secondary/60 p-6"><h2 className="mb-4 text-xl font-bold text-label-primary">{title}</h2><MarkdownRenderer content={content} /></div> :
        <div className="space-y-6">
          <div className="grid gap-6 md:grid-cols-2"><div className="space-y-1.5"><Label>عنوان</Label><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="عنوان مقاله" /></div><div className="space-y-1.5"><Label>اسلاگ</Label><Input value={slug} onChange={e => setSlug(e.target.value)} placeholder="my-post-slug" dir="ltr" /></div></div>
          <div className="space-y-1.5"><Label>خلاصه</Label><Textarea value={excerpt} onChange={e => setExcerpt(e.target.value)} placeholder="خلاصه‌ای کوتاه از مقاله" className="h-24" /></div>
          <div className="space-y-1.5"><Label>محتوا (Markdown)</Label><Textarea value={content} onChange={e => setContent(e.target.value)} placeholder="محتوای مقاله را با فرمت Markdown وارد کنید..." className="min-h-[320px] font-mono text-sm" /></div>
          <div className="grid gap-6 md:grid-cols-2"><div className="space-y-1.5"><Label>تگ اصلی / شاخه علمی</Label><Select value={categoryId} onChange={e => setCategoryId(Number(e.target.value))}><option value="">یکی از ۵ شاخه اصلی را انتخاب کنید</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><p className="text-xs leading-6 text-label-tertiary">این فیلد همان تگ رنگی اصلی روی کارت و صفحه مقاله است. شاخه‌های پیشنهادی: فیزیک، شیمی، زیست/پزشکی، زمین و فضا، هوش مصنوعی/فناوری/داده.</p></div><div className="space-y-1.5"><Label>وضعیت</Label><Select value={status} onChange={e => setStatus(e.target.value as "draft" | "published")}><option value="draft">پیش‌نویس</option><option value="published">منتشر شده</option></Select></div></div>
          <div className="space-y-1.5"><Label>تصویر شاخص</Label><div className="flex items-center gap-3"><Button type="button" variant="outline" onClick={() => setMediaOpen(true)} className="gap-2"><ImageIcon className="h-4 w-4" />{coverImageId ? "تغییر تصویر" : "انتخاب تصویر"}</Button>{coverImageId && <Button type="button" variant="ghost" onClick={() => setCoverImageId(null)}>حذف</Button>}</div>{coverImageId && <img src={media.find(m => m.id === coverImageId)?.url} alt="cover" className="mt-3 h-40 rounded-ios object-cover" />}</div>
          {mediaOpen && <div className="rounded-ios border border-separator/30 bg-bg-secondary/60 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold text-label-primary">انتخاب تصویر</span><Button variant="ghost" size="sm" onClick={() => setMediaOpen(false)}>بستن</Button></div><div className="grid max-h-64 gap-3 overflow-y-auto sm:grid-cols-3">{media.map(m => <button key={m.id} type="button" onClick={() => { setCoverImageId(m.id); setMediaOpen(false); }} className={`overflow-hidden rounded-ios border-2 p-1 transition-colors ${coverImageId === m.id ? "border-ios-blue" : "border-transparent"}`}><img src={m.url} alt={m.alt || ""} className="h-24 w-full object-cover" /></button>)}</div></div>}
          <div className="space-y-1.5"><Label>تگ‌های مرتبط / زیرشاخه‌ها</Label><p className="text-xs leading-6 text-label-tertiary">این تگ‌ها به صورت چیپ‌های خاکستری کوچک کنار تگ اصلی نمایش داده می‌شوند و برای زیرشاخه‌های علوم، مسیرهای مرتبط و جستجوی موضوعی هستند.</p><div className="flex flex-wrap gap-2">{tags.map(t => <button key={t.id} type="button" onClick={() => toggleTag(t.id)} className={`rounded-full px-3 py-1 text-sm transition-colors ${selectedTagIds.includes(t.id) ? "bg-ios-blue text-white" : "bg-fill-quaternary text-label-secondary hover:bg-fill-tertiary"}`}>{t.name}</button>)}</div></div>
          <div className="grid gap-6 md:grid-cols-2"><div className="space-y-1.5"><Label>عنوان SEO</Label><Input value={metaTitle} onChange={e => setMetaTitle(e.target.value)} placeholder="عنوان برای موتورهای جستجو" /></div><div className="space-y-1.5"><Label>Canonical URL</Label><Input value={canonicalUrl} onChange={e => setCanonicalUrl(e.target.value)} placeholder="https://..." dir="ltr" /></div></div>
          <div className="space-y-1.5"><Label>توضیحات SEO</Label><Textarea value={metaDescription} onChange={e => setMetaDescription(e.target.value)} placeholder="توضیحات کوتاه برای موتورهای جستجو" className="h-24" /></div>
          <div className="space-y-1.5"><Label>منابع</Label><Textarea value={sources} onChange={e => setSources(e.target.value)} placeholder="منابع مقاله را اینجا وارد کنید" className="h-32" /></div>
          <div className="grid gap-6 md:grid-cols-2"><div className="space-y-1.5"><Label>آدرس ویدیو</Label><Input value={videoUrl} onChange={e => setVideoUrl(e.target.value)} placeholder="https://..." dir="ltr" /></div><div className="space-y-1.5"><Label>پوستر ویدیو</Label><Input value={videoPoster} onChange={e => setVideoPoster(e.target.value)} placeholder="https://..." dir="ltr" /></div></div>
          <div className="grid gap-6 md:grid-cols-2"><div className="space-y-1.5"><Label>لینک بحث تلگرام</Label><Input value={telegramDiscussionUrl} onChange={e => setTelegramDiscussionUrl(e.target.value)} placeholder="https://t.me/..." dir="ltr" /></div><div className="flex items-center gap-3 pt-6"><input type="checkbox" id="featured" checked={featured} onChange={e => setFeatured(e.target.checked)} className="h-4 w-4" /><Label htmlFor="featured" className="cursor-pointer">مقاله ویژه</Label></div></div>
          {postId && <div className="rounded-ios border border-separator/30 bg-fill-quaternary/40 p-4"><div className="text-sm font-semibold text-label-secondary mb-2">آمار (فقط خواندنی)</div><div className="grid gap-4 md:grid-cols-2"><div className="text-sm text-label-primary">بازدید: {viewCount || 0}</div><div className="text-sm text-label-primary">لایک: {likeCount || 0}</div></div></div>}
        </div>}
    </div>
  );
}
